
import __ASTRO_IMAGE_IMPORT_rr8IY from "./projects/armored_buggy_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FArmoredBuggy.json";
import __ASTRO_IMAGE_IMPORT_2ow9Cc from "./projects/behemoth_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FBehemoth.json";
import __ASTRO_IMAGE_IMPORT_2whKHr from "./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FArmoredBuggy.json";
import __ASTRO_IMAGE_IMPORT_eIzue from "./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FBehemoth.json";
import __ASTRO_IMAGE_IMPORT_Zc2oHn from "./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FRubbleTanker.json";
import __ASTRO_IMAGE_IMPORT_ZxbHx5 from "./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FRubbleTug.json";
import __ASTRO_IMAGE_IMPORT_2uzPbm from "./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FTransporter.json";
import __ASTRO_IMAGE_IMPORT_Z2bDoBt from "./projects/rubble_tug_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FRubbleTug.json";
import __ASTRO_IMAGE_IMPORT_ZviwVn from "./projects/transporter_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FTransporter.json";
export default new Map([["./projects/armored_buggy_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FArmoredBuggy.json", __ASTRO_IMAGE_IMPORT_rr8IY], ["./projects/behemoth_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FBehemoth.json", __ASTRO_IMAGE_IMPORT_2ow9Cc], ["./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FArmoredBuggy.json", __ASTRO_IMAGE_IMPORT_2whKHr], ["./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FBehemoth.json", __ASTRO_IMAGE_IMPORT_eIzue], ["./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FRubbleTanker.json", __ASTRO_IMAGE_IMPORT_Zc2oHn], ["./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FRubbleTug.json", __ASTRO_IMAGE_IMPORT_ZxbHx5], ["./projects/rubble_tanker_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FTransporter.json", __ASTRO_IMAGE_IMPORT_2uzPbm], ["./projects/rubble_tug_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FRubbleTug.json", __ASTRO_IMAGE_IMPORT_Z2bDoBt], ["./projects/transporter_cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fworks%2FTransporter.json", __ASTRO_IMAGE_IMPORT_ZviwVn]]);
		